name: Java CI with Maven

on:
  push:
    branches:
      - main
    paths:
      - 'pom.xml'
      - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Build
        run: mvn clean install

      - name: Fail if tests fail
        if: ${{ steps.build.exit_code != 0 }}
        run: exit 1
